from django import forms
from .models import Report

class ReportFilterForm(forms.Form):
    report_type = forms.ChoiceField(
        choices=[('', 'All Types')] + list(Report.ReportType.choices),
        required=False,
        label='Report Type',
    )
    generated_by = forms.CharField(
        required=False,
        label='Generated By (Name or Email)',
        widget=forms.TextInput(attrs={'placeholder': 'Name or Email'})
    )
    date_from = forms.DateField(
        required=False,
        label='From',
        widget=forms.DateInput(attrs={'type': 'date'})
    )
    date_to = forms.DateField(
        required=False,
        label='To',
        widget=forms.DateInput(attrs={'type': 'date'})
    )
