# Generated by Django 4.2.9 on 2025-06-20 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('students_looking', models.PositiveIntegerField(default=0)),
                ('students_waiting', models.PositiveIntegerField(default=0)),
                ('students_ongoing', models.PositiveIntegerField(default=0)),
                ('students_completed', models.PositiveIntegerField(default=0)),
                ('total_companies', models.PositiveIntegerField(default=0)),
                ('active_companies', models.PositiveIntegerField(default=0)),
                ('total_internships', models.PositiveIntegerField(default=0)),
                ('active_internships', models.PositiveIntegerField(default=0)),
                ('total_applications', models.PositiveIntegerField(default=0)),
                ('pending_applications', models.PositiveIntegerField(default=0)),
                ('accepted_applications', models.PositiveIntegerField(default=0)),
                ('rejected_applications', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('STUDENT_LIST', 'Student List'), ('OJT_TRACKING', 'OJT Tracking Sheet'), ('COMPANY_LIST', 'Company List'), ('APPLICATION_SUMMARY', 'Application Summary')], max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
