# Generated by Django 4.2.9 on 2025-08-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Auto-generated thumbnail for preview', null=True, upload_to='report_previews/'),
        ),
    ]
