# Generated by Django 4.2.9 on 2025-07-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviserprofile',
            name='year_levels',
            field=models.CharField(blank=True, help_text='Comma-separated year levels handled (e.g. 1,2,3)', max_length=20),
        ),
    ]
