# Generated by Django 4.2.9 on 2025-08-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adviserprofile_year_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, help_text='Student ID number', max_length=32, null=True, unique=True),
        ),
    ]
