# Generated by Django 4.2.9 on 2025-08-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adviserprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='coordinatorprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='adviserprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='adviser_profiles/'),
        ),
        migrations.AddField(
            model_name='coordinatorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='coordinator_profiles/'),
        ),
    ]
