# Generated by Django 4.2.9 on 2025-08-13 01:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_adviserprofile_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Start of the week (Monday)')),
                ('week_end', models.DateField(help_text='End of the week (Sunday)')),
                ('file', models.FileField(upload_to='dtr_files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('hours_rendered', models.PositiveIntegerField(default=0, help_text='OJT hours rendered for this week')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtrs', to='accounts.adviserprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtrs', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('student', 'week_start')},
            },
        ),
    ]
