# Generated by Django 4.2.9 on 2025-08-13 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_dtr'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocument',
            name='adviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to='accounts.adviserprofile'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='adviser_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
