# Generated by Django 4.2.9 on 2025-08-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentdocument_adviser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdocument',
            name='adviser',
        ),
        migrations.RemoveField(
            model_name='studentdocument',
            name='adviser_remarks',
        ),
        migrations.RemoveField(
            model_name='studentdocument',
            name='status',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='ojt_status',
            field=models.CharField(choices=[('LOOKING', 'Still Looking'), ('WAITING', 'Waiting for Response'), ('ONGOING', 'Currently Undergoing OJT'), ('REJECTED', 'All Applications Rejected')], default='LOOKING', max_length=20),
        ),
    ]
