# Generated by Django 4.2.9 on 2025-08-13 09:09

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_studentdocument_adviser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requireddocument',
            name='template_file',
            field=models.FileField(blank=True, help_text='PDF template for this document (uploaded by coordinator)', null=True, upload_to='document_templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='file',
            field=models.FileField(upload_to=accounts.models.student_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='ojt_status',
            field=models.CharField(choices=[('LOOKING', 'Still Looking'), ('WAITING', 'Waiting for Response'), ('ONGOING', 'Currently Undergoing OJT'), ('REJECTED', 'All Applications Rejected'), ('COMPLETED', 'Completed')], default='LOOKING', max_length=20),
        ),
    ]
