# Generated by Django 4.2.9 on 2025-08-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_requireddocument_template_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocument',
            name='approved',
            field=models.BooleanField(default=False, help_text='Set to True when adviser accepts the document'),
        ),
    ]
