# Generated by Django 4.2.9 on 2026-01-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='For advisers: requires coordinator approval. Students and coordinators are auto-approved.'),
        ),
    ]
