# Generated by Django 4.2.9 on 2026-01-17 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_company_company_type'),
        ('accounts', '0013_deactivationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_internship',
            field=models.ForeignKey(blank=True, help_text='The accepted internship application where the student is currently placed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placed_student', to='internship.application'),
        ),
    ]
