# Generated by Django 4.2.9 on 2026-05-24 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_master_list_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('TECHNICAL', 'Technical'), ('SOFT', 'Soft')], default='TECHNICAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='advisermasterlistentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='advisermasterlistupload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='template_file',
            field=models.FileField(blank=True, help_text='DOCX template for this document (uploaded by coordinator)', null=True, upload_to='document_templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='ojt_status',
            field=models.CharField(blank=True, choices=[('LOOKING', 'Still Looking'), ('WAITING', 'Waiting for Response'), ('ONGOING', 'Currently Undergoing OJT'), ('REJECTED', 'All Applications Rejected'), ('COMPLETED', 'Completed')], default=None, max_length=20, null=True),
        ),
    ]
