# Generated by Django 4.2.9 on 2025-11-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('GOVERNMENT', 'Government'), ('NGO', 'Non-Governmental Organization'), ('ACADEMIC', 'Academic/School'), ('OTHER', 'Other')], default='PRIVATE', max_length=20),
        ),
    ]
