# Generated by Django 4.2.9 on 2026-05-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_custom_submission_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_partner',
            field=models.BooleanField(default=False),
        ),
    ]
