# Generated by ChatGPT on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internship", "0004_company_is_partner"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("feature_order", models.JSONField()),
                ("coef", models.JSONField()),
                ("intercept", models.FloatField(default=0.0)),
                ("sample_count", models.PositiveIntegerField(default=0)),
                ("accuracy", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
